from BaseClasses import MultiWorld
from typing import TypedDict, List, Dict, NamedTuple
from BaseClasses import ItemClassification, Item
from worlds.pokemon_colo.Helpers import PCItemType
from .Strings import Items, Events
from .Options import ColosseumOptions, RuiUnlock, ColosseumSanity

base_id = 159700

class PCItemData(NamedTuple):
    item_id: int = -1 # Internal item ID
    item_type: PCItemType = PCItemType.NONE
    amount: int = -1

class ColosseumItem(Item):
    game: str = "Pokemon Colosseum"

class ItemDesc(TypedDict):
    name: str
    count: int
    classification: ItemClassification
    data: PCItemData

shadow_pokemon: List[ItemDesc] = [
    {'name': Items.Progression.makuhita,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': None},
    {'name': Items.Progression.bayleaf,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': None},
    {'name': Items.Progression.quilava,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': None},
    {'name': Items.Progression.croconaw,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': None},
    {'name': Items.Progression.slugma,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': None},
    {'name': Items.Progression.misdreavus,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': None},
    {'name': Items.Progression.noctowl,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': None},
    {'name': Items.Progression.flaffy,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': None},
    {'name': Items.Progression.skiploom,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': None},
    {'name': Items.Progression.quagsire,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': None},
    {'name': Items.Progression.furret,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': None},
    {'name': Items.Progression.yanma,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': None},
    {'name': Items.Progression.remoraid,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': None},
    {'name': Items.Progression.mantine,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': None},
    {'name': Items.Progression.qwilfish,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': None},
    {'name': Items.Progression.meditite,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': None},
    {'name': Items.Progression.dunsparce,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': None},
    {'name': Items.Progression.swablu,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': None},
    {'name': Items.Progression.sudowoodo,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': None},
    {'name': Items.Progression.hitmontop,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': None},
    {'name': Items.Progression.entei,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': None},
    {'name': Items.Progression.ledian,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': None},
    {'name': Items.Progression.suicune,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': None},
    {'name': Items.Progression.gligar,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': None},
    {'name': Items.Progression.stantler,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': None},
    {'name': Items.Progression.piloswine,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': None},
    {'name': Items.Progression.sneasel,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': None},
    {'name': Items.Progression.aipom,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': None},
    {'name': Items.Progression.murkrow,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': None},
    {'name': Items.Progression.forretress,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': None},
    {'name': Items.Progression.ariados,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': None},
    {'name': Items.Progression.granbull,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': None},
    {'name': Items.Progression.vibrava,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': None},
    {'name': Items.Progression.raikou,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': None},
    {'name': Items.Progression.sunflora,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': None},
    {'name': Items.Progression.delibird,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': None},
    {'name': Items.Progression.heracross,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': None},
    {'name': Items.Progression.skarmory,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': None},
    {'name': Items.Progression.miltank,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': None},
    {'name': Items.Progression.absol,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': None},
    {'name': Items.Progression.houndoom,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': None},
    {'name': Items.Progression.tropius,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': None},
    {'name': Items.Progression.metagross,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': None},
    {'name': Items.Progression.tyranitar,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': None}
]

post_game_shadows: List[ItemDesc] = [
    {'name': Items.Progression.smeargle,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': None},
    {'name': Items.Progression.ursaring,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': None},
    {'name': Items.Progression.shuckle,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': None},
    {'name': Items.Progression.togetic,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': None}
]

prog_items: List[ItemDesc] = [
    {'name': Items.Progression.region_unlock,
     'count': 4,
     'classification': ItemClassification.progression,
     'data': None},
    {'name': Items.Progression.gear,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': None},
    {'name': Items.Progression.red_id,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': None},
    {'name': Items.Progression.green_id,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': None},
    {'name': Items.Progression.blue_id,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': None},
    {'name': Items.Progression.yellow_id,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': None},
    {'name': Items.Progression.colosseum_unlock,
     'count': 4,
     'classification': ItemClassification.progression,
     'data': None},
    {'name': Items.Progression.rui,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': None},
    {'name': Items.Progression.small_tablet,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': None},
    {'name': Items.Progression.f_disk,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': None},
    {'name': Items.Progression.time_flute, # Only 1 is progression, do not know how to get the other two as useful
     'count': 3,
     'classification': ItemClassification.progression,
     'data': None},
    {'name': Items.Progression.jail_key,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': None},
    {'name': Items.Progression.elevator_key,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': None},
    {'name': Items.Progression.powerup_part,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': None},
    {'name': Items.Progression.r_disk,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': None},
    {'name': Items.Progression.subway_key,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': None},
    {'name': Items.Progression.u_disk,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': None},
    {'name': Items.Progression.maingate_key,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': None},
    {'name': Items.Progression.card_key,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': None},
    {'name': Items.Progression.down_st_key,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': None},
    {'name': Items.Progression.data_rom,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': None}
]

colosseum_round_items: List[ItemDesc] = [
    {'name': Items.Progression.phenac_round_pass,
     'count': 3,
     'classification': ItemClassification.progression,
     'data': None},
    {'name': Items.Progression.pyrite_round_pass,
     'count': 4,
     'classification': ItemClassification.progression,
     'data': None},
    {'name': Items.Progression.under_round_pass,
     'count': 3,
     'classification': ItemClassification.progression,
     'data': None},
    {'name': Items.Progression.deep_round_pass,
     'count': 4,
     'classification': ItemClassification.progression,
     'data': None}
]

useful_items: List[ItemDesc] = [
    {'name': Items.Useful.ein_file_h,
     'count': 1,
     'classification': ItemClassification.useful,
     'data': None},
    {'name': Items.Useful.ein_file_s,
     'count': 1,
     'classification': ItemClassification.useful,
     'data': None},
    {'name': Items.Useful.ein_file_p,
     'count': 1,
     'classification': ItemClassification.useful,
     'data': None},
    {'name': Items.Useful.ein_file_c,
     'count': 1,
     'classification': ItemClassification.useful,
     'data': None},
    {'name': Items.Useful.ein_file_f,
     'count': 1,
     'classification': ItemClassification.useful,
     'data': None},
    {'name': Items.Useful.exp_share,
     'count': 1,
     'classification': ItemClassification.useful,
     'data': None},
    {'name': Items.Useful.quick_claw,
     'count': 1,
     'classification': ItemClassification.useful,
     'data': None},
    {'name': Items.Useful.silk_scarf,
     'count': 1,
     'classification': ItemClassification.useful,
     'data': None},
    {'name': Items.Useful.dna_sample,
     'count': 3,
     'classification': ItemClassification.useful,
     'data': None}
]

filler: List[ItemDesc] = [
    {'name': Items.Filler.pokeball,
     'count': 1,
     'classification': ItemClassification.filler,
     'data': PCItemData(item_id=4, item_type=PCItemType.ITEM, amount=5)},
    {'name': Items.Filler.greatball,
     'count': 1,
     'classification': ItemClassification.filler,
     'data': PCItemData(item_id=3, item_type=PCItemType.ITEM, amount=3)},
    {'name': Items.Filler.ultraball,
     'count': 1,
     'classification': ItemClassification.filler,
     'data': PCItemData(item_id=2, item_type=PCItemType.ITEM, amount=2)},
    {'name': Items.Filler.timerball,
     'count': 1,
     'classification': ItemClassification.filler,
     'data': PCItemData(item_id=10, item_type=PCItemType.ITEM, amount=1)},
    {'name': Items.Filler.carbos,
     'count': 1,
     'classification': ItemClassification.filler,
     'data': PCItemData(item_id=66, item_type=PCItemType.ITEM, amount=1)},
    {'name': Items.Filler.zinc,
     'count': 1,
     'classification': ItemClassification.filler,
     'data': PCItemData(item_id=70, item_type=PCItemType.ITEM, amount=1)},
    {'name': Items.Filler.iron,
     'count': 1,
     'classification': ItemClassification.filler,
     'data': PCItemData(item_id=65, item_type=PCItemType.ITEM, amount=1)},
    {'name': Items.Filler.protein,
     'count': 1,
     'classification': ItemClassification.filler,
     'data': PCItemData(item_id=64, item_type=PCItemType.ITEM, amount=1)}
]

event_items: List[ItemDesc] = [
    {'name': Events.goal,
     'count': 0, # In case it somehow get into used_items it will not be added
     'classification': ItemClassification.progression}
]

all_items = prog_items + shadow_pokemon + useful_items + filler + colosseum_round_items + post_game_shadows + event_items

def set_items_used(options: ColosseumOptions) -> List[ItemDesc]:
    # Set items to be used in the multiworld here to used_items
    used_items = []
    used_items.extend(prog_items)
    used_items.extend(shadow_pokemon)

    if options.postgame_shadow_pokemon:
        used_items.extend(post_game_shadows)

    used_items.extend(useful_items)
    if options.colosseum_sanity != ColosseumSanity.option_off:
        used_items.extend(colosseum_round_items)
    return used_items