from BaseClasses import MultiWorld
from typing import TypedDict, List, Dict, NamedTuple
from BaseClasses import ItemClassification, Item
from worlds.pokemon_colo.Helpers import PCItemType
from .Strings import Items, Events
from .Options import ColosseumOptions, RuiUnlock, ColosseumSanity

base_id = 159700

class PCItemData(NamedTuple):
    item_id: int = -1
    """
    Internal item ID. If a Pokemon, is the Pokemon's internal ID
    """
    item_type: PCItemType = PCItemType.NONE
    amount: int = -1
    shadow_id: int = -1
    """
    Used only for the Pokemon PCItemType. Denotes what the shadow ID should be.
    """

class ColosseumItem(Item):
    game: str = "Pokemon Colosseum"

class ItemDesc(TypedDict):
    name: str
    count: int
    classification: ItemClassification
    data: PCItemData

shadow_pokemon: List[ItemDesc] = [
    {'name': Items.Progression.makuhita,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': PCItemData(item_id=335, item_type=PCItemType.POKEMON, amount=1, shadow_id=1)},
    {'name': Items.Progression.bayleaf,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': PCItemData(item_id=152, item_type=PCItemType.POKEMON, amount=1, shadow_id=2)},
    {'name': Items.Progression.quilava,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': PCItemData(item_id=156, item_type=PCItemType.POKEMON, amount=1, shadow_id=3)},
    {'name': Items.Progression.croconaw,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': PCItemData(item_id=159, item_type=PCItemType.POKEMON, amount=1, shadow_id=4)},
    {'name': Items.Progression.slugma,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': PCItemData(item_id=218, item_type=PCItemType.POKEMON, amount=1, shadow_id=5)},
    {'name': Items.Progression.misdreavus,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': PCItemData(item_id=200, item_type=PCItemType.POKEMON, amount=1, shadow_id=6)},
    {'name': Items.Progression.noctowl,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': PCItemData(item_id=164, item_type=PCItemType.POKEMON, amount=1, shadow_id=7)},
    {'name': Items.Progression.flaffy,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': PCItemData(item_id=180, item_type=PCItemType.POKEMON, amount=1, shadow_id=8)},
    {'name': Items.Progression.skiploom,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': PCItemData(item_id=188, item_type=PCItemType.POKEMON, amount=1, shadow_id=9)},
    {'name': Items.Progression.quagsire,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': PCItemData(item_id=195, item_type=PCItemType.POKEMON, amount=1, shadow_id=10)},
    {'name': Items.Progression.furret,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': PCItemData(item_id=162, item_type=PCItemType.POKEMON, amount=1, shadow_id=11)},
    {'name': Items.Progression.yanma,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': PCItemData(item_id=193, item_type=PCItemType.POKEMON, amount=1, shadow_id=12)},
    {'name': Items.Progression.remoraid,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': PCItemData(item_id=223, item_type=PCItemType.POKEMON, amount=1, shadow_id=13)},
    {'name': Items.Progression.mantine,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': PCItemData(item_id=226, item_type=PCItemType.POKEMON, amount=1, shadow_id=14)},
    {'name': Items.Progression.qwilfish,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': PCItemData(item_id=211, item_type=PCItemType.POKEMON, amount=1, shadow_id=15)},
    {'name': Items.Progression.meditite,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': PCItemData(item_id=336, item_type=PCItemType.POKEMON, amount=1, shadow_id=16)},
    {'name': Items.Progression.dunsparce,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': PCItemData(item_id=206, item_type=PCItemType.POKEMON, amount=1, shadow_id=17)},
    {'name': Items.Progression.swablu,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': PCItemData(item_id=338, item_type=PCItemType.POKEMON, amount=1, shadow_id=18)},
    {'name': Items.Progression.sudowoodo,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': PCItemData(item_id=185, item_type=PCItemType.POKEMON, amount=1, shadow_id=19)},
    {'name': Items.Progression.hitmontop,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': PCItemData(item_id=237, item_type=PCItemType.POKEMON, amount=1, shadow_id=20)},
    {'name': Items.Progression.entei,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': PCItemData(item_id=244, item_type=PCItemType.POKEMON, amount=1, shadow_id=21)},
    {'name': Items.Progression.ledian,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': PCItemData(item_id=166, item_type=PCItemType.POKEMON, amount=1, shadow_id=22)},
    {'name': Items.Progression.suicune,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': PCItemData(item_id=245, item_type=PCItemType.POKEMON, amount=1, shadow_id=23)},
    {'name': Items.Progression.gligar,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': PCItemData(item_id=207, item_type=PCItemType.POKEMON, amount=1, shadow_id=24)},
    {'name': Items.Progression.stantler,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': PCItemData(item_id=234, item_type=PCItemType.POKEMON, amount=1, shadow_id=25)},
    {'name': Items.Progression.piloswine,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': PCItemData(item_id=221, item_type=PCItemType.POKEMON, amount=1, shadow_id=26)},
    {'name': Items.Progression.sneasel,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': PCItemData(item_id=215, item_type=PCItemType.POKEMON, amount=1, shadow_id=27)},
    {'name': Items.Progression.aipom,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': PCItemData(item_id=190, item_type=PCItemType.POKEMON, amount=1, shadow_id=28)},
    {'name': Items.Progression.murkrow,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': PCItemData(item_id=198, item_type=PCItemType.POKEMON, amount=1, shadow_id=29)},
    {'name': Items.Progression.forretress,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': PCItemData(item_id=205, item_type=PCItemType.POKEMON, amount=1, shadow_id=30)},
    {'name': Items.Progression.ariados,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': PCItemData(item_id=168, item_type=PCItemType.POKEMON, amount=1, shadow_id=31)},
    {'name': Items.Progression.granbull,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': PCItemData(item_id=210, item_type=PCItemType.POKEMON, amount=1, shadow_id=32)},
    {'name': Items.Progression.vibrava,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': PCItemData(item_id=333, item_type=PCItemType.POKEMON, amount=1, shadow_id=33)},
    {'name': Items.Progression.raikou,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': PCItemData(item_id=243, item_type=PCItemType.POKEMON, amount=1, shadow_id=34)},
    {'name': Items.Progression.sunflora,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': PCItemData(item_id=192, item_type=PCItemType.POKEMON, amount=1, shadow_id=35)},
    {'name': Items.Progression.delibird,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': PCItemData(item_id=225, item_type=PCItemType.POKEMON, amount=1, shadow_id=36)},
    {'name': Items.Progression.heracross,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': PCItemData(item_id=214, item_type=PCItemType.POKEMON, amount=1, shadow_id=37)},
    {'name': Items.Progression.skarmory,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': PCItemData(item_id=227, item_type=PCItemType.POKEMON, amount=1, shadow_id=38)},
    {'name': Items.Progression.miltank,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': PCItemData(item_id=241, item_type=PCItemType.POKEMON, amount=1, shadow_id=39)},
    {'name': Items.Progression.absol,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': PCItemData(item_id=376, item_type=PCItemType.POKEMON, amount=1, shadow_id=40)},
    {'name': Items.Progression.houndoom,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': PCItemData(item_id=229, item_type=PCItemType.POKEMON, amount=1, shadow_id=41)},
    {'name': Items.Progression.tropius,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': PCItemData(item_id=369, item_type=PCItemType.POKEMON, amount=1, shadow_id=42)},
    {'name': Items.Progression.metagross,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': PCItemData(item_id=400, item_type=PCItemType.POKEMON, amount=1, shadow_id=43)},
    {'name': Items.Progression.tyranitar,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': PCItemData(item_id=248, item_type=PCItemType.POKEMON, amount=1, shadow_id=44)}
]

post_game_shadows: List[ItemDesc] = [
    {'name': Items.Progression.smeargle,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': PCItemData(item_id=235, item_type=PCItemType.POKEMON, amount=1, shadow_id=45)},
    {'name': Items.Progression.ursaring,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': PCItemData(item_id=217, item_type=PCItemType.POKEMON, amount=1, shadow_id=46)},
    {'name': Items.Progression.shuckle,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': PCItemData(item_id=213, item_type=PCItemType.POKEMON, amount=1, shadow_id=47)},
    {'name': Items.Progression.togetic,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': PCItemData(item_id=176, item_type=PCItemType.POKEMON, amount=1, shadow_id=48)}
]

prog_items: List[ItemDesc] = [
    {'name': Items.Progression.region_unlock,
     'count': 4,
     'classification': ItemClassification.progression,
     'data': None},
    {'name': Items.Progression.gear,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': None},
    {'name': Items.Progression.red_id,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': None},
    {'name': Items.Progression.green_id,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': None},
    {'name': Items.Progression.blue_id,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': None},
    {'name': Items.Progression.yellow_id,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': None},
    {'name': Items.Progression.colosseum_unlock,
     'count': 4,
     'classification': ItemClassification.progression,
     'data': None},
    {'name': Items.Progression.rui,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': None},
    {'name': Items.Progression.small_tablet,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': None},
    {'name': Items.Progression.f_disk,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': None},
    {'name': Items.Progression.time_flute, # Only 1 is progression, do not know how to get the other two as useful
     'count': 3,
     'classification': ItemClassification.progression,
     'data': None},
    {'name': Items.Progression.jail_key,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': None},
    {'name': Items.Progression.elevator_key,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': None},
    {'name': Items.Progression.powerup_part,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': None},
    {'name': Items.Progression.r_disk,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': None},
    {'name': Items.Progression.subway_key,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': None},
    {'name': Items.Progression.u_disk,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': None},
    {'name': Items.Progression.maingate_key,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': None},
    {'name': Items.Progression.card_key,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': None},
    {'name': Items.Progression.down_st_key,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': None},
    {'name': Items.Progression.data_rom,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': None}
]

colosseum_round_items: List[ItemDesc] = [
    {'name': Items.Progression.phenac_round_pass,
     'count': 3,
     'classification': ItemClassification.progression,
     'data': None},
    {'name': Items.Progression.pyrite_round_pass,
     'count': 4,
     'classification': ItemClassification.progression,
     'data': None},
    {'name': Items.Progression.under_round_pass,
     'count': 3,
     'classification': ItemClassification.progression,
     'data': None},
    {'name': Items.Progression.deep_round_pass,
     'count': 4,
     'classification': ItemClassification.progression,
     'data': None}
]

useful_items: List[ItemDesc] = [
    {'name': Items.Useful.ein_file_h,
     'count': 1,
     'classification': ItemClassification.useful,
     'data': None},
    {'name': Items.Useful.ein_file_s,
     'count': 1,
     'classification': ItemClassification.useful,
     'data': None},
    {'name': Items.Useful.ein_file_p,
     'count': 1,
     'classification': ItemClassification.useful,
     'data': None},
    {'name': Items.Useful.ein_file_c,
     'count': 1,
     'classification': ItemClassification.useful,
     'data': None},
    {'name': Items.Useful.ein_file_f,
     'count': 1,
     'classification': ItemClassification.useful,
     'data': None},
    {'name': Items.Useful.exp_share,
     'count': 1,
     'classification': ItemClassification.useful,
     'data': None},
    {'name': Items.Useful.quick_claw,
     'count': 1,
     'classification': ItemClassification.useful,
     'data': None},
    {'name': Items.Useful.silk_scarf,
     'count': 1,
     'classification': ItemClassification.useful,
     'data': None},
    {'name': Items.Useful.dna_sample,
     'count': 3,
     'classification': ItemClassification.useful,
     'data': None}
]

filler: List[ItemDesc] = [
    {'name': Items.Filler.pokeball,
     'count': 1,
     'classification': ItemClassification.filler,
     'data': PCItemData(item_id=4, item_type=PCItemType.ITEM, amount=5)},
    {'name': Items.Filler.greatball,
     'count': 1,
     'classification': ItemClassification.filler,
     'data': PCItemData(item_id=3, item_type=PCItemType.ITEM, amount=3)},
    {'name': Items.Filler.ultraball,
     'count': 1,
     'classification': ItemClassification.filler,
     'data': PCItemData(item_id=2, item_type=PCItemType.ITEM, amount=2)},
    {'name': Items.Filler.timerball,
     'count': 1,
     'classification': ItemClassification.filler,
     'data': PCItemData(item_id=10, item_type=PCItemType.ITEM, amount=1)},
    {'name': Items.Filler.carbos,
     'count': 1,
     'classification': ItemClassification.filler,
     'data': PCItemData(item_id=66, item_type=PCItemType.ITEM, amount=1)},
    {'name': Items.Filler.zinc,
     'count': 1,
     'classification': ItemClassification.filler,
     'data': PCItemData(item_id=70, item_type=PCItemType.ITEM, amount=1)},
    {'name': Items.Filler.iron,
     'count': 1,
     'classification': ItemClassification.filler,
     'data': PCItemData(item_id=65, item_type=PCItemType.ITEM, amount=1)},
    {'name': Items.Filler.protein,
     'count': 1,
     'classification': ItemClassification.filler,
     'data': PCItemData(item_id=64, item_type=PCItemType.ITEM, amount=1)}
]

event_items: List[ItemDesc] = [
    {'name': Events.goal,
     'count': 0, # In case it somehow get into used_items it will not be added
     'classification': ItemClassification.progression}
]

all_items = prog_items + shadow_pokemon + useful_items + filler + colosseum_round_items + post_game_shadows + event_items

def set_items_used(options: ColosseumOptions) -> List[ItemDesc]:
    # Set items to be used in the multiworld here to used_items
    used_items = []
    used_items.extend(prog_items)
    used_items.extend(shadow_pokemon)

    if options.postgame_shadow_pokemon:
        used_items.extend(post_game_shadows)

    used_items.extend(useful_items)
    if options.colosseum_sanity != ColosseumSanity.option_off:
        used_items.extend(colosseum_round_items)
    return used_items